## 2.3.2 Numpy Operation

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a + 5

array([ 5,  6,  7,  8,  9, 10])

In [4]:
b = np.random.randint(1, 5, 20).reshape(4, 5)
b

array([[2, 2, 4, 4, 1],
       [4, 4, 1, 2, 1],
       [3, 4, 1, 2, 4],
       [3, 4, 1, 1, 4]])

In [5]:
b * 3

array([[ 6,  6, 12, 12,  3],
       [12, 12,  3,  6,  3],
       [ 9, 12,  3,  6, 12],
       [ 9, 12,  3,  3, 12]])

In [6]:
c = np.arange(10000)
%timeit c + 1

3.9 µs ± 84.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
%timeit [i + 1 for i in c]

3.35 ms ± 190 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
a = np.random.randint(1, 5, (5, 4))
a

array([[2, 1, 1, 4],
       [4, 3, 3, 2],
       [3, 3, 1, 1],
       [1, 3, 4, 1],
       [4, 4, 2, 1]])

In [22]:
b = np.ones((5, 4), dtype=int)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
a + b

array([[3, 2, 2, 5],
       [5, 4, 4, 3],
       [4, 4, 2, 2],
       [2, 4, 5, 2],
       [5, 5, 3, 2]])

In [25]:
c = np.random.randint(1, 5, (3, 4))
c

array([[3, 4, 4, 2],
       [2, 4, 2, 2],
       [1, 2, 3, 1]])

In [26]:
d = np.random.randint(1, 5, (3, 4))
d

array([[4, 4, 1, 2],
       [1, 3, 2, 3],
       [1, 3, 3, 1]])

In [27]:
c * d

array([[12, 16,  4,  4],
       [ 2, 12,  4,  6],
       [ 1,  6,  9,  1]])

In [28]:
a = np.random.randint(1, 5, (3, 2))
b = np.random.randint(1, 5, (2, 3))

In [29]:
a

array([[2, 3],
       [1, 2],
       [1, 1]])

In [30]:
b

array([[3, 2, 4],
       [4, 1, 2]])

In [31]:
np.dot(a, b)

array([[18,  7, 14],
       [11,  4,  8],
       [ 7,  3,  6]])

In [32]:
a = np.random.randint(1, 5, (5, 4))
a

array([[4, 2, 4, 3],
       [3, 1, 4, 3],
       [1, 1, 3, 4],
       [1, 4, 3, 2],
       [2, 3, 3, 3]])

In [33]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [34]:
a + b

array([[4, 3, 6, 6],
       [3, 2, 6, 6],
       [1, 2, 5, 7],
       [1, 5, 5, 5],
       [2, 4, 5, 6]])

In [35]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [36]:
a + c

ValueError: operands could not be broadcast together with shapes (5,4) (5,) 

In [37]:
c = np.arange(5).reshape(5, 1)
c

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [38]:
a + c

array([[4, 2, 4, 3],
       [4, 2, 5, 4],
       [3, 3, 5, 6],
       [4, 7, 6, 5],
       [6, 7, 7, 7]])

In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b 

array([False,  True, False,  True])

In [40]:
a > b

array([False, False,  True, False])

In [41]:
(a == b).all()

False

In [42]:
(a == b).any()

True

In [43]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [44]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

In [45]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [46]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [47]:
a = np.random.randint(1, 5, 6)
a

array([4, 1, 2, 1, 4, 4])

In [49]:
a.sum()

16

In [50]:
a.mean()

2.6666666666666665

In [51]:
a.std()

1.3743685418725535

In [53]:
a.min()

1

In [54]:
a.max()

4

In [55]:
# return index
a.argmin()

1

In [56]:
# return index
a.argmax()

0

In [57]:
b = np.random.randint(1, 5, (6, 4))
b

array([[2, 4, 2, 4],
       [1, 4, 2, 1],
       [2, 4, 2, 4],
       [1, 1, 1, 1],
       [4, 4, 1, 1],
       [4, 3, 4, 4]])

In [58]:
b.sum()

61

In [59]:
b.sum(axis=0)

array([14, 20, 12, 15])

In [60]:
b.sum(axis=1)

array([12,  8, 12,  4, 10, 15])

In [61]:
b.sum(axis=1).sum()

61

In [62]:
b.min(axis=1)

array([2, 1, 2, 1, 1, 3])

In [63]:
# return index
b.argmin(axis=1)

array([0, 0, 0, 0, 2, 1])

In [64]:
b.std(axis=1)

array([1.        , 1.22474487, 1.        , 0.        , 1.5       ,
       0.4330127 ])