## 2.3.1 Numpy Array

In [14]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [15]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [16]:
b = np.array([[1, 2], [3, 4], [5, 6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
# View the attributes of the array, including the dimensions and type of the data.
b.ndim

2

In [18]:
b.shape

(3, 2)

In [19]:
# View the data type of the elements in the array.
b.dtype

dtype('int64')

In [20]:
# Generate continuous array.
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Divide [0,2] into an 11 equidistant array.
d = np.linspace(0, 2, 11)
d

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [22]:
# Generate a 3x3 array with a value of 1.
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# Generate a 3x6 array with a value of 0.
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
# Return a 2-D 4x4 array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
# Generate a 6x4 random array
np.random.randn(6, 4)

array([[ 2.18236371, -0.51302686,  1.27130212, -0.67853037],
       [ 0.63814752,  0.20803139,  0.34799744, -1.06350592],
       [ 0.10881847,  0.41940459,  0.66114975,  1.24044069],
       [ 0.83779514,  0.30250688, -0.54838873,  1.57852699],
       [-1.94281016, -1.05807358, -0.22595654,  1.63594336],
       [-0.98048837, -0.68367434,  2.11366906,  0.01701044]])

In [27]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a[0], a[3], a[-1]

(0, 3, 9)

In [29]:
a[:4]

array([0, 1, 2, 3])

In [30]:
a[3:7]

array([3, 4, 5, 6])

In [31]:
a[6:]

array([6, 7, 8, 9])

In [32]:
a[2:8:2]

array([2, 4, 6])

In [33]:
a[2::2]

array([2, 4, 6, 8])

In [34]:
a[::3]

array([0, 3, 6, 9])

In [36]:
a = np.arange(0, 51, 10).reshape(6, 1) + np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [37]:
a[0, 0], a[2, -1]

(0, 25)

In [39]:
a[0, 2:5]

array([2, 3, 4])

In [40]:
a[:3, 3:]

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25]])

In [41]:
a [2, :]

array([20, 21, 22, 23, 24, 25])

In [42]:
a[:, 3]

array([ 3, 13, 23, 33, 43, 53])

In [43]:
a[:, ::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24],
       [30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

In [44]:
a[::2, ::3]

array([[ 0,  3],
       [20, 23],
       [40, 43]])

In [45]:
a = np.random.randint(10, 20, 6)
a

array([19, 14, 19, 18, 18, 19])

In [46]:
a % 2 == 0

array([False,  True, False,  True,  True, False])

In [47]:
a[a % 2 == 0]

array([14, 18, 18])

In [48]:
a = np.arange(0, 51, 10).reshape(6, 1) + np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [49]:
a[a % 2 == 0]

array([ 0,  2,  4, 10, 12, 14, 20, 22, 24, 30, 32, 34, 40, 42, 44, 50, 52,
       54])

In [50]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [51]:
b = a[2:5]
b

array([2, 3, 4])

In [52]:
b[1] = 100
b

array([  2, 100,   4])

In [53]:
a

array([  0,   1,   2, 100,   4,   5])

In [54]:
np.may_share_memory(a, b)

True

In [55]:
b = a[2:6].copy()
b

array([  2, 100,   4,   5])

In [56]:
b[1] = 3
b

array([2, 3, 4, 5])

In [57]:
a

array([  0,   1,   2, 100,   4,   5])

In [58]:
np.may_share_memory(a, b)

False